#!/usr/bin/env python

import rospy
from node_alive import AutoStarter


if __name__ == "__main__":
    rospy.init_node('auto_starter', anonymous=False)

    autostarter = AutoStarter()
    rate = rospy.Rate(10.0)
    while not rospy.is_shutdown():
        autostarter.update()
        rate.sleep()

    autostarter.stop()
