#!/usr/bin/env python

import sys
import roslaunch.config
import roslaunch.xmlloader
import roslaunch.rlutil
import roslaunch.core
import os
from optparse import OptionParser
import rosnode
import time
import re

import roslib
import rospy

from std_msgs.msg import String

roslib.load_manifest('node_alive')

def get_node_names(roslaunch_files):
	loader = roslaunch.xmlloader.XmlLoader(resolve_anon=True)
	config = roslaunch.config.load_config_default(roslaunch_files, None, loader=loader, verbose=False, assign_machines=False)

	node_names = []
	for node in config.nodes:
		node_names.append(node.name)
	return node_names

# Main function.
if __name__ == '__main__':
	rospy.init_node('node_alive_add')

	parser = OptionParser(usage="usage: \tget_node_names [roslaunch_file]")

	options, args = parser.parse_args()
	if not args:
		parser.error('please specify a roslaunch_file')

	pub = rospy.Publisher('check_alive_nodes', String)

	for node in get_node_names([args[0]]):	
		pub.publish(str(node))
		rospy.loginfo("Added '%s' to node_alive_server"%node)
