#!/usr/bin/env python

import roslaunch.config
import roslaunch.xmlloader
import roslaunch.rlutil
import roslaunch.core
from optparse import OptionParser
import rospy

from std_msgs.msg import String


def get_node_names(roslaunch_files):
    loader = roslaunch.xmlloader.XmlLoader(resolve_anon=True)
    config = roslaunch.config.load_config_default(roslaunch_files, None, loader=loader, verbose=False,
                                                  assign_machines=False)

    node_names = []
    for node in config.nodes:
        node_names.append(node.namespace + node.name)
    return node_names


if __name__ == '__main__':
    rospy.init_node('node_alive_add')

    parser = OptionParser(usage="usage: \t node_alive_add [roslaunch_file]")

    options, args = parser.parse_args()
    if not args:
        parser.error('please specify a roslaunch_file')

    pub = rospy.Publisher('check_alive_nodes', String)

    for node in get_node_names([args[0]]):
        if node[-4:] != "_tmp":
            pub.publish(node)
            rospy.loginfo("Adding '%s' to node_alive_server" % node)
